version: "3"

services:
  rom-sql:
    build:
      context: .
    env_file: .env
    entrypoint: /bin/bash -c '(bundle check || bundle) && tail -f Gemfile'
    volumes:
      - .:/usr/local/src/rom-sql
      - bundle:/usr/local/bundle
    depends_on: [mysql, postgres]
    links: [mysql, postgres]

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    env_file: .env

  postgres:
    image: postgres:11
    ports:
      - "5433:5432"
    env_file: .env

volumes:
  bundle:
